using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace taskD03
{
    public class Complex
    {
        #region Data Fields
        int real;
        int img;

        public int Real
        {
            get
            {
                return real;
            }

            set
            {
                real = value;
            }
        }

        public int Img
        {
            get
            {
                return img;
            }

            set
            {
                img = value;
            }
        }
        #endregion

        #region Print
        public string Print(/*Complex this,*/)
        {
            //if()
            return $"{this.Real}+{Img}i";
        }
        #endregion
        #region Function to Add 2 Complex Numbers

        //caller c1
        public Complex Add(/*Complex this,*/Complex right)
        {
            Complex result = new Complex();
            result.Real = this.Real + right.Real;
            result.Img = Img + right.Img;
            return result;
        }
        #endregion


        #region Ctors
        //default ctor generated by o.s [CLR] if there is no such ctor
        public Complex()
        {
            Real = 3; Img = 4;
        }
        public Complex(int _real, int _img)
        {
            Real = _real;
            Img = _img;
        }
        public Complex(int _num)
        {
            Real = Img = _num;
        }
        #endregion
    }
}
